export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_SPOTIFY_USER_DATA = "GET_SPOTIFY_USER_DATA";
export const GET_SPOTIFY_RECENTLY_PLAYED = "GET_SPOTIFY_RECENTLY_PLAYED";
export const SET_SPOTIFY_ACCESS_TOKEN = "SET_SPOTIFY_ACCESS_TOKEN";
export const SET_LANDING_TOKEN = "SET_LANDING_TOKEN";
